name: Convert and Deploy GeoJSON to PMTiles and FlatGeobuf

on:
  schedule:
    - cron: "0 0 * * *" # 毎日 UTC 0時に実行
  workflow_dispatch:

jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: shiworks/tippecanoe-gdal:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup directories and convert GeoJSONs
        run: |
          mkdir -p FlatGeobuf
          mkdir -p PMTiles
          mkdir -p GeoJSON

          declare -A urls=(
            ["unkohonsu2024_rosen_kukan"]="https://gtfs-gis.jp/railway_honsu/data/unkohonsu2024_rosen_kukan.geojson"
            ["unkohonsu2024_kukan"]="https://gtfs-gis.jp/railway_honsu/data/unkohonsu2024_kukan.geojson"
            ["unkohonsu2024_kukan_eki"]="https://gtfs-gis.jp/railway_honsu/data/unkohonsu2024_kukan_eki.geojson"
            ["unkohonsu2024_rosen_eki"]="https://gtfs-gis.jp/railway_honsu/data/unkohonsu2024_rosen_eki.geojson"
            ["unkohonsu2024_eki"]="https://gtfs-gis.jp/railway_honsu/data/unkohonsu2024_eki.geojson"
            ["unkohonsu2023_rosen_kukan"]="https://gtfs-gis.jp/railway_honsu/data/unkohonsu2023_rosen_kukan.geojson"
            ["unkohonsu2023_kukan"]="https://gtfs-gis.jp/railway_honsu/data/unkohonsu2023_kukan.geojson"
            ["unkohonsu2023_kukan_eki"]="https://gtfs-gis.jp/railway_honsu/data/unkohonsu2023_kukan_eki.geojson"
            ["unkohonsu2023_rosen_eki"]="https://gtfs-gis.jp/railway_honsu/data/unkohonsu2023_rosen_eki.geojson"
            ["unkohonsu2023_eki"]="https://gtfs-gis.jp/railway_honsu/data/unkohonsu2023_eki.geojson"
          )
          for key in "${!urls[@]}"; do
            curl -o "GeoJSON/$key.geojson" "${urls[$key]}"
            ogr2ogr -f FlatGeobuf "FlatGeobuf/$key.fgb" "GeoJSON/$key.geojson"
          done

      - name: Convert FlatGeobuf to PMTiles
        run: |
          for f in FlatGeobuf/*.fgb; do
            base=$(basename $f .fgb)
            tippecanoe -o PMTiles/${base}.pmtiles --force $f -pf -pk
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "y.shiwaku.5519@gmail.com"
          git config --local user.name "shi-works"
          git add FlatGeobuf PMTiles GeoJSON/
          git commit -m "Update GeoJSON, FlatGeobuf, and PMTiles files"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./PMTiles
